### ISSUE TITLE
Issue related to https://github.com/noahcoolboy/funcaptcha

### ISSUE THREAD

**Issue by Oli2004** [noahcoolboy/roblox-funcaptcha#17]
As i previously stated. roblox login funcaptcha is only returning access_denied even tho i did add the blob like you said before.

**Comment by Oli2004** [comment]
TypeError: Cannot read properties of undefined (reading 'startsWith')
    at new Session (/root/FunPass/node_modules/funcaptcha/lib/session.js:28:25)
    at /root/FunPass/index.js:185:23
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by Draugr-official** [comment]
https://github.com/noahcoolboy/roblox-funcaptcha/blob/master/readme.md#currently-unmaintained
"CURRENTLY UNMAINTAINED"
